apiVersion: sts.plus/v1alpha1
kind: PhasedRollout
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"sts.plus/v1alpha1","kind":"PhasedRollout","metadata":{"annotations":{},"labels":{"app.kubernetes.io/created-by":"sts-plus-operator","app.kubernetes.io/instance":"phasedrollout-sample","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"phasedrollout","app.kubernetes.io/part-of":"sts-plus-operator"},"name":"phasedrollout-sample","namespace":"default"},"spec":{"check":{"failureThreshold":3,"initialDelaySeconds":30,"maxTries":10,"periodSeconds":30,"query":{"expr":"up{}","secretRef":"promSecret","url":"prom:9000/xx"},"successThreshold":3},"rollback":false,"skipCheck":false,"targetRef":"web"}}
  creationTimestamp: "2022-11-13T13:34:43Z"
  generation: 3
  labels:
    app.kubernetes.io/created-by: sts-plus-operator
    app.kubernetes.io/instance: phasedrollout-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: phasedrollout
    app.kubernetes.io/part-of: sts-plus-operator
  name: web2
  namespace: default
  resourceVersion: "90014"
  uid: 0a1d1e95-b603-42e9-951f-352367ffd568
spec:
  check:
    failureThreshold: 4
    initialDelaySeconds: 30
    maxTries: 11
    periodSeconds: 30
    query:
      expr: up{}
      secretRef: prom-secret
      url: prom:9000/xx
    successThreshold: 3
  skipCheck: false
  targetRef: web
