apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    sts.plus/phasedRollout: phasedrollout-sample
  creationTimestamp: "2022-11-13T13:35:22Z"
  generation: 9
  name: web2
  namespace: default
  resourceVersion: "104593"
  uid: 09e9db11-601f-470c-bd78-c2d4e34ce260
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: registry.k8s.io/nginx-slim:0.8
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 81
          name: web
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 3
    type: RollingUpdate
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: web-86bbb5b47d
  observedGeneration: 9
  readyReplicas: 3
  replicas: 3
  updateRevision: web-86bbb5b47d
  updatedReplicas: 3
