---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-sts-plus-v1alpha1-phasedrollout
  failurePolicy: Ignore
  name: mphasedrollout-v1alpha1.kb.io
  rules:
  - apiGroups:
    - sts.plus
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - phasedrollouts
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-sts-plus-v1alpha1-phasedrollout
  failurePolicy: Ignore
  name: vphasedrollout-v1alpha1.kb.io
  rules:
  - apiGroups:
    - sts.plus
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - phasedrollouts
  sideEffects: None
