# permissions for end users to view phasedrollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sts-phased-rollout-operator
    app.kubernetes.io/managed-by: kustomize
  name: phasedrollout-viewer-role
rules:
- apiGroups:
  - sts.plus
  resources:
  - phasedrollouts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sts.plus
  resources:
  - phasedrollouts/status
  verbs:
  - get
