apiVersion: sts.plus/v1alpha1
kind: PhasedRollout
metadata:
  labels:
    app.kubernetes.io/name: phasedrollout
    app.kubernetes.io/instance: phasedrollout-sample
    app.kubernetes.io/part-of: sts-plus-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sts-plus-operator
  name: phasedrollout-sample
spec:
  targetRef: web
  skipCheck: false
  check:
    initialDelaySeconds: 30
    periodSeconds: 30
    maxTries: 10
    successThreshold: 3
    failureThreshold: 3
    query:
      expr: "up{}"
      url: prom:9000/xx
      secretRef: promSecret
