apiVersion: sts.plus/v1alpha1
kind: PhasedRollout
metadata:
  labels:
    app.kubernetes.io/name: phasedrollout
    app.kubernetes.io/instance: phasedrollout-sample
    app.kubernetes.io/part-of: sts-plus-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sts-plus-operator
  name: phasedrollout-sample
spec:
  # TODO(user): Add fields here
