apiVersion: sts.plus/v1alpha1
kind: PhasedRollout
metadata:
  labels:
    app.kubernetes.io/name: sts-phased-rollout-operator
    app.kubernetes.io/managed-by: kustomize
  name: phasedrollout-sample
  namespace: sample
spec:
  targetRef: web
  standardRollingUpdate: false
  check:
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 3
    query:
      expr: "up{}"
      url: http://prometheus-prometheus.monitoring:9090
