name: ci

on:

  workflow_dispatch:
    inputs:
      dry_run:
       description: 'DryRun'
       required: true
       default: 'true'

  push:
    tags:
      - 'v*'
    branches:
      - 'main'
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

  pull_request:
    branches:
      - 'main'
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:

  ci:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: test
        run: make test

      - name: Bump version
        # bump version only if it was not already specified
        if: github.ref_type != 'tag'
        id: bump_verison
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch_all_tags: true
          # really create a new version only if it is a push on main (e.g. workflow dispatch or pull request is a dry run)
          dry_run: ${{ ! (github.event_name == 'push' && github.ref == 'refs/heads/main') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: dbonfigli/sts-phased-rollout-operator

      - name: Log in to Docker Hub
        if: github.ref_type == 'tag' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'false')
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: ${{ github.ref_type == 'tag' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'false') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
